version: "3.1"
services:
  database:
    image: postgres:14.1-alpine3.15
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_DB=willagropastoral"
      - "POSTGRES_USER=willagropastoral"
      - "POSTGRES_PASSWORD=iamgroot"
  